### ISSUE TITLE
LVM partitions not listed

### ISSUE THREAD

**Issue by sgurnick** [rapidloop/rtop#15]
I'm not sure if this is a feature request or bug - rtop does not list partitions that use LVM.

It lists the boot partition, since this is not using LVM. However my root filesystem is on a LVM partition and this is not listed/monitored in the Filesystem section of the report.

**Comment by mdevan** [comment]
Can you post the output of "df"?

**Comment by sgurnick** [comment]
```
$ df -k
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/VolGroup-lv_root
                      49064776   7208044  39364316  16% /
tmpfs                   506352         0    506352   0% /dev/shm
/dev/sda1               495844     70488    399756  15% /boot
```
When I run rtop against this remote host I only see the /boot partition in the Filesystem list.

**Comment by mdevan** [comment]
Thanks for that. rtop doesn't like that the line got split in two. Will fix. Just for reference, what is the linux distro and version that you're using? On a Debian 7, the same command does not split the lines:

    $ df -k
    Filesystem                                             1K-blocks    Used Available Use% Mounted on
    rootfs                                                   7688360 3991436   3306372  55% /
    udev                                                       10240       0     10240   0% /dev
    tmpfs                                                      49512     300     49212   1% /run
    /dev/disk/by-uuid/66db3c4b-a3d3-44c6-8c9d-21416b9885dd   7688360 3991436   3306372  55% /
    tmpfs                                                       5120       0      5120   0% /run/lock
    tmpfs                                                     214100       4    214096   1% /run/shm

**Comment by sgurnick** [comment]
I am running rtop on a RHEL6 system and the remote host is also RHEL6. 

Thank you for checking into this.
