### ISSUE TITLE
[OS X] rtop: asn1: structure error: length too large

### ISSUE THREAD

**Issue by hwmattk** [rapidloop/rtop#16]
Built as "git clone --recursive http://github.com/rapidloop/rtop; make". Calling "rtop [ipaddress]" returns only error "rtop: asn1: structure error: length too large" and terminates.

**Comment by frederic-jomedia** [comment]
same for me.
I used brew to install go :
go version go1.4.2 darwin/amd64

**Comment by mpe** [comment]
Likewise on Ubuntu 14.10 with ```go version go1.4.1 linux/amd64```.

From the stock ```golang-go 2:1.4.1-1ubuntu1``` package.

**Comment by thechriswalker** [comment]
Likewise on Debian Wheezy with official go 1.4 package.
`go version go1.4 linux/amd64`

**Comment by dirtyvader** [comment]
Likewise on ArchLinux (latest updates)
go version go1.4.2 linux/amd64

**Comment by runar** [comment]
Please use issue #3 :+1:

**Comment by mdevan** [comment]
Please check with commit f753d19. With this rtop will natively support encrypted private keys, and also support auth via ssh-agent correctly.

**Comment by steveh** [comment]
Still failing on f753d19 on OSX 10.10.4. It's a 4096-bit encrypted RSA key.

**Comment by frederic-jomedia** [comment]
I confirm that it fixed my problem

**Comment by mdevan** [comment]
Try with the latest commit ba5b35e. This improves the auth method handling.

**Comment by mattiasgeniar** [comment]
Problem still exists for me.

```
$ git remote -v
origin	http://github.com/rapidloop/rtop (fetch)
origin	http://github.com/rapidloop/rtop (push)

$ git pull
Already up-to-date

$ ./rtop server.tld
rtop: asn1: structure error: length too large
```

Using a standard 2048 RSA key (with passphrase) on Mac OSX Yosemite.

```
$ ssh-keygen -l -f ~/.ssh/id_rsa | awk '{print $1, $NF}'
2048 (RSA)
```

Is there any other info I can give you to help troubleshoot this?

**Comment by mattiasgeniar** [comment]
This fixes it for me indeed. Don't forget, after ```git pull``` you need a ```make``` too!
