### ISSUE TITLE
Use SSH config

### ISSUE THREAD

**Issue by jeroenvisser101** [rapidloop/rtop#2]
Currently, there's no way to use your `~/.ssh/config` as a host. It'll just say that no such host is resolvable. It would be cool if that would also work.

**Comment by felixmc** [comment]
Came here to suggest the same thing! it would be especially useful for servers that require a long ssh config

**Comment by kwo** [comment]
+1

**Comment by jbub** [comment]
Would be awesome.

**Comment by marthjod** [comment]
+1

**Comment by sricola** [comment]
+1

**Comment by kenetik** [comment]
+1

Also came here to suggest same thing!

**Comment by heliostatic** [comment]
:+1:

**Comment by dullgiulio** [comment]
Could this help? https://github.com/dullgiulio/sshconfig

I can also try to integrate it myself and make a PR, but I am unavailable for the next week.

**Comment by jeroenvisser101** [comment]
Hmmm, that's pretty nice!

**Comment by NickWoodhams** [comment]
+1

**Comment by shilov** [comment]
+1

**Comment by mdevan** [comment]
We currently have something in the works that will read sshconfig. Stay tuned.

**Comment by mdevan** [comment]
Available with d57695c. Check it out and report any issues!

**Comment by jeroenvisser101** [comment]
Nice! Thanks @mdevan :)
