### ISSUE TITLE
error when using encrypted private key

### ISSUE THREAD

**Issue by phime42** [rapidloop/rtop#21]
rtop: x509: failed to parse EC private key: asn1: structure error: length too large

**Comment by vrillusions** [comment]
I have this working with an encrypted key but mine is a standard RSA key:

```shell
$ ssh-keygen -l -f ~/.ssh/id_rsa | awk '{print $1, $NF}'
2048 (RSA)
```

What's the output when you run that, may help him diagnose it.  (not a dev, just a user that happened to see this and wanted to help a bit)

**Comment by mdevan** [comment]
Try with the latest commit ba5b35e. This improves the auth method handling.

**Comment by mdevan** [comment]
Please open a new issue if problem still persists.
