### ISSUE TITLE
Unreadable when light theme

### ISSUE THREAD

**Issue by davetoxa** [rapidloop/rtop#22]
![rtop -rtop track2win 146 185 139 43-22 -i key 1 rtop 1 2015-05-19 01-23-46](https://cloud.githubusercontent.com/assets/417317/7691773/eafac65e-fdc5-11e4-9a55-718fbb838faa.png)

**Comment by vassilevsky** [comment]
I use the Tomorrow theme in iTerm and the metrics are *completely* blank, not visible at all :)
