### ISSUE TITLE
Replace previous data

### ISSUE THREAD

**Issue by nicofrand** [rapidloop/rtop#25]
When I let rtop run, it will display the new results below the previous results. It would be much clearer if it replaced it.

![rtop-clear-previous-data](https://cloud.githubusercontent.com/assets/3419050/8548435/0b267218-24c5-11e5-9e9e-f28f7a78b9d7.png)

**Comment by mdevan** [comment]
Hmm, it tries to do that, of course (see file main.go, function showStats). The ANSI sequence esc[2J should clear the screen. There must be something slightly different with your term? What's the value of $TERM?

BTW, you probably want to redact your IP from the image.

**Comment by nicofrand** [comment]
```console
nicofrand@desktop:~/rtop$ echo $TERM
xterm
```

Thanks, I updated the screenshot !

**Comment by nicofrand** [comment]
Hi again, I guess I scrolled by mistake + I thought "clear" was actually clearing eveything and not just shifting the output upwards. 
Plus, in Konsole "reset" does not work. See http://askubuntu.com/questions/25077/how-to-really-clear-the-terminal.

I am closing this issue.

**Comment by mdevan** [comment]
Good to know, thanks for the follow up!
