### ISSUE TITLE
Question - Wondering if anyone knows it this works on the RaspberryPi 2

### ISSUE THREAD

**Issue by joeblew99** [rapidloop/rtop#29]
Just wanting to ask first before i try.

Since its go, a very good chance. If anyone can comment would be great.

**Comment by mdevan** [comment]
Yes, you should be able to build and run rtop on RPi 2 and even on RPi 1B+. It should also be possible to use rtop from another machine to monitor an RPi.

Do add a note if you find any issues.

**Comment by joeblew99** [comment]
@mdevan awesome thanks - will give it a go..

also do you know if it works on windows 10 ? We have some machines on that too, but eventually will get rid of them.

**Comment by mdevan** [comment]
You can build it and run it on a Windows 10, but can do only password-less ssh and ssh-agent. It can't read passwords from command-line -- patches welcome!

**Comment by joeblew99** [comment]
ok super cool - thanks for feedback.
Will give this a go, and happy to make a PR on anything i hit.
