### ISSUE TITLE
Json Output Option

### ISSUE THREAD

**Issue by aminearbi** [rapidloop/rtop#36]
Is it possible to return a json formatted output?

**Comment by mdevan** [comment]
Shouldn't be too difficult. Try replacing showStats() in main.go with whatever type of output you want. Maybe something like:

```go
func showStats(output io.Writer, client *ssh.Client) {
	stats := Stats{}
	getAllStats(client, &stats)
	json.NewEncoder(output).Encode(stats)
}
```
